### ISSUE TITLE
Is this still being maintained?

### ISSUE THREAD

**Issue by zllovesuki** [intech/moleculer-elastic-apm#2]
Upstream `elastic-apm-node` is now 2.x, and do you have any plans to keep this plugin updated?

**Comment by intech** [comment]
Of course! After all, there was an opportunity to trace microservices. When I first developed this module, it could only record transactional requests from the molecular server. There was still no single mechanism for intercepting errors. Now all this is possible to implement and I am already working as a free time in the opentracing branch.
Thank you for your attention to my work! :)

**Comment by zllovesuki** [comment]
Thank you for contributing to the Moleculer ecosystem 😄
